; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py

; RUN: llc -mtriple=riscv64 -mattr=+experimental-ztt -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV64

define void @test_mabs_ew() {
; RV64-LABEL: test_mabs_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mabs.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mabs.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mabs.ew(i64, i64)

define void @test_mcolunzip_ew() {
; RV64-LABEL: test_mcolunzip_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mcolunzip.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcolunzip.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mcolunzip.ew(i64, i64)

define void @test_mcolzip_ew() {
; RV64-LABEL: test_mcolzip_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mcolzip.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcolzip.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mcolzip.ew(i64, i64)

define void @test_mconv_ew() {
; RV64-LABEL: test_mconv_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mconv.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mconv.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mconv.ew(i64, i64)

define void @test_mexp2_ew() {
; RV64-LABEL: test_mexp2_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mexp2.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mexp2.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mexp2.ew(i64, i64)

define void @test_mlog2_ew() {
; RV64-LABEL: test_mlog2_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mlog2.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mlog2.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mlog2.ew(i64, i64)

define void @test_mprefixadd_col() {
; RV64-LABEL: test_mprefixadd_col:
; RV64:       # %bb.0:
; RV64-NEXT:    mprefixadd.col m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mprefixadd.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mprefixadd.col(i64, i64)

define void @test_mprefixadd_row() {
; RV64-LABEL: test_mprefixadd_row:
; RV64:       # %bb.0:
; RV64-NEXT:    mprefixadd.row m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mprefixadd.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mprefixadd.row(i64, i64)

define void @test_mprefixmax_col() {
; RV64-LABEL: test_mprefixmax_col:
; RV64:       # %bb.0:
; RV64-NEXT:    mprefixmax.col m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mprefixmax.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mprefixmax.col(i64, i64)

define void @test_mprefixmax_row() {
; RV64-LABEL: test_mprefixmax_row:
; RV64:       # %bb.0:
; RV64-NEXT:    mprefixmax.row m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mprefixmax.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mprefixmax.row(i64, i64)

define void @test_mreduceadd_col() {
; RV64-LABEL: test_mreduceadd_col:
; RV64:       # %bb.0:
; RV64-NEXT:    mreduceadd.col m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mreduceadd.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mreduceadd.col(i64, i64)

define void @test_mreduceadd_row() {
; RV64-LABEL: test_mreduceadd_row:
; RV64:       # %bb.0:
; RV64-NEXT:    mreduceadd.row m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mreduceadd.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mreduceadd.row(i64, i64)

define void @test_mreducemax_col() {
; RV64-LABEL: test_mreducemax_col:
; RV64:       # %bb.0:
; RV64-NEXT:    mreducemax.col m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mreducemax.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mreducemax.col(i64, i64)

define void @test_mreducemax_row() {
; RV64-LABEL: test_mreducemax_row:
; RV64:       # %bb.0:
; RV64-NEXT:    mreducemax.row m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mreducemax.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mreducemax.row(i64, i64)

define void @test_mrowunzip_ew() {
; RV64-LABEL: test_mrowunzip_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mrowunzip.ew m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mrowunzip.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mrowunzip.ew(i64, i64)

define void @test_mabsdiff_ew() {
; RV64-LABEL: test_mabsdiff_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mabsdiff.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mabsdiff.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mabsdiff.ew(i64, i64, i64)

define void @test_madd_ew() {
; RV64-LABEL: test_madd_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    madd.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.madd.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.madd.ew(i64, i64, i64)

define void @test_mand_ew() {
; RV64-LABEL: test_mand_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mand.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mand.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mand.ew(i64, i64, i64)

define void @test_mandnot_ew() {
; RV64-LABEL: test_mandnot_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mandnot.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mandnot.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mandnot.ew(i64, i64, i64)

define void @test_mcmovge_ew() {
; RV64-LABEL: test_mcmovge_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mcmovge.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcmovge.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mcmovge.ew(i64, i64, i64)

define void @test_mcmovlt_ew() {
; RV64-LABEL: test_mcmovlt_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mcmovlt.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcmovlt.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mcmovlt.ew(i64, i64, i64)

define void @test_mcmpge_ew() {
; RV64-LABEL: test_mcmpge_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mcmpge.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcmpge.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mcmpge.ew(i64, i64, i64)

define void @test_mcmplt_ew() {
; RV64-LABEL: test_mcmplt_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mcmplt.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcmplt.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mcmplt.ew(i64, i64, i64)

define void @test_mgather_ew() {
; RV64-LABEL: test_mgather_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mgather.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mgather.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mgather.ew(i64, i64, i64)

define void @test_mhdiff_ew() {
; RV64-LABEL: test_mhdiff_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mhdiff.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mhdiff.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mhdiff.ew(i64, i64, i64)

define void @test_mldexp_ew() {
; RV64-LABEL: test_mldexp_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mldexp.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mldexp.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mldexp.ew(i64, i64, i64)

define void @test_mldexpacc_ew() {
; RV64-LABEL: test_mldexpacc_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mldexpacc.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mldexpacc.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mldexpacc.ew(i64, i64, i64)

define void @test_mlog2sub_ew() {
; RV64-LABEL: test_mlog2sub_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mlog2sub.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mlog2sub.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mlog2sub.ew(i64, i64, i64)

define void @test_mmax_ew() {
; RV64-LABEL: test_mmax_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmax.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmax.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmax.ew(i64, i64, i64)

define void @test_mmean_ew() {
; RV64-LABEL: test_mmean_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmean.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmean.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmean.ew(i64, i64, i64)

define void @test_mmin_ew() {
; RV64-LABEL: test_mmin_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmin.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmin.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmin.ew(i64, i64, i64)

define void @test_mmul_ew() {
; RV64-LABEL: test_mmul_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmul.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmul.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmul.ew(i64, i64, i64)

define void @test_mmulacc_ew() {
; RV64-LABEL: test_mmulacc_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulacc.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulacc.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulacc.ew(i64, i64, i64)

define void @test_mmulaccneg_ew() {
; RV64-LABEL: test_mmulaccneg_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulaccneg.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulaccneg.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulaccneg.ew(i64, i64, i64)

define void @test_mmuladd_ew() {
; RV64-LABEL: test_mmuladd_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmuladd.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmuladd.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmuladd.ew(i64, i64, i64)

define void @test_mmulneg_ew() {
; RV64-LABEL: test_mmulneg_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulneg.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulneg.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulneg.ew(i64, i64, i64)

define void @test_mmulsub_ew() {
; RV64-LABEL: test_mmulsub_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulsub.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulsub.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulsub.ew(i64, i64, i64)

define void @test_mor_ew() {
; RV64-LABEL: test_mor_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mor.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mor.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mor.ew(i64, i64, i64)

define void @test_mornot_ew() {
; RV64-LABEL: test_mornot_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mornot.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mornot.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mornot.ew(i64, i64, i64)

define void @test_mrdexp_ew() {
; RV64-LABEL: test_mrdexp_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mrdexp.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mrdexp.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mrdexp.ew(i64, i64, i64)

define void @test_mrdexpacc_ew() {
; RV64-LABEL: test_mrdexpacc_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mrdexpacc.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mrdexpacc.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mrdexpacc.ew(i64, i64, i64)

define void @test_mrowzip_ew() {
; RV64-LABEL: test_mrowzip_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mrowzip.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mrowzip.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mrowzip.ew(i64, i64, i64)

define void @test_mscatadd_col() {
; RV64-LABEL: test_mscatadd_col:
; RV64:       # %bb.0:
; RV64-NEXT:    mscatadd.col m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mscatadd.col(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mscatadd.col(i64, i64, i64)

define void @test_mscatadd_row() {
; RV64-LABEL: test_mscatadd_row:
; RV64:       # %bb.0:
; RV64-NEXT:    mscatadd.row m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mscatadd.row(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mscatadd.row(i64, i64, i64)

define void @test_mscatmax_col() {
; RV64-LABEL: test_mscatmax_col:
; RV64:       # %bb.0:
; RV64-NEXT:    mscatmax.col m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mscatmax.col(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mscatmax.col(i64, i64, i64)

define void @test_mscatmax_row() {
; RV64-LABEL: test_mscatmax_row:
; RV64:       # %bb.0:
; RV64-NEXT:    mscatmax.row m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mscatmax.row(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mscatmax.row(i64, i64, i64)

define void @test_mselge_ew() {
; RV64-LABEL: test_mselge_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mselge.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mselge.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mselge.ew(i64, i64, i64)

define void @test_msellt_ew() {
; RV64-LABEL: test_msellt_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    msellt.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.msellt.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.msellt.ew(i64, i64, i64)

define void @test_msub_ew() {
; RV64-LABEL: test_msub_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    msub.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.msub.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.msub.ew(i64, i64, i64)

define void @test_msublog2_ew() {
; RV64-LABEL: test_msublog2_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    msublog2.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.msublog2.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.msublog2.ew(i64, i64, i64)

define void @test_mxor_ew() {
; RV64-LABEL: test_mxor_ew:
; RV64:       # %bb.0:
; RV64-NEXT:    mxor.ew m1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mxor.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mxor.ew(i64, i64, i64)

define void @test_mabsdiff_ew_x(i64 %a1) {
; RV64-LABEL: test_mabsdiff_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mabsdiff.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mabsdiff.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mabsdiff.ew.x(i64, i64, i64)

define void @test_madd_ew_x(i64 %a1) {
; RV64-LABEL: test_madd_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    madd.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.madd.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.madd.ew.x(i64, i64, i64)

define void @test_mand_ew_x(i64 %a1) {
; RV64-LABEL: test_mand_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mand.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mand.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mand.ew.x(i64, i64, i64)

define void @test_mandnot_ew_x(i64 %a1) {
; RV64-LABEL: test_mandnot_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mandnot.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mandnot.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mandnot.ew.x(i64, i64, i64)

define void @test_mcmpge_ew_x(i64 %a1) {
; RV64-LABEL: test_mcmpge_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mcmpge.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcmpge.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mcmpge.ew.x(i64, i64, i64)

define void @test_mcmplt_ew_x(i64 %a1) {
; RV64-LABEL: test_mcmplt_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mcmplt.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mcmplt.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mcmplt.ew.x(i64, i64, i64)

define void @test_mhdiff_ew_x(i64 %a1) {
; RV64-LABEL: test_mhdiff_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mhdiff.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mhdiff.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mhdiff.ew.x(i64, i64, i64)

define void @test_mldexp_ew_x(i64 %a1) {
; RV64-LABEL: test_mldexp_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mldexp.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mldexp.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mldexp.ew.x(i64, i64, i64)

define void @test_mldexpacc_ew_x(i64 %a1) {
; RV64-LABEL: test_mldexpacc_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mldexpacc.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mldexpacc.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mldexpacc.ew.x(i64, i64, i64)

define void @test_mlog2sub_ew_x(i64 %a1) {
; RV64-LABEL: test_mlog2sub_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mlog2sub.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mlog2sub.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mlog2sub.ew.x(i64, i64, i64)

define void @test_mmax_ew_x(i64 %a1) {
; RV64-LABEL: test_mmax_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmax.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmax.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmax.ew.x(i64, i64, i64)

define void @test_mmean_ew_x(i64 %a1) {
; RV64-LABEL: test_mmean_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmean.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmean.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmean.ew.x(i64, i64, i64)

define void @test_mmin_ew_x(i64 %a1) {
; RV64-LABEL: test_mmin_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmin.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmin.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmin.ew.x(i64, i64, i64)

define void @test_mmul_ew_x(i64 %a1) {
; RV64-LABEL: test_mmul_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmul.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmul.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmul.ew.x(i64, i64, i64)

define void @test_mmulacc_ew_x(i64 %a1) {
; RV64-LABEL: test_mmulacc_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulacc.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulacc.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmulacc.ew.x(i64, i64, i64)

define void @test_mmulaccneg_ew_x(i64 %a1) {
; RV64-LABEL: test_mmulaccneg_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulaccneg.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulaccneg.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmulaccneg.ew.x(i64, i64, i64)

define void @test_mmuladd_ew_x(i64 %a1) {
; RV64-LABEL: test_mmuladd_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmuladd.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmuladd.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmuladd.ew.x(i64, i64, i64)

define void @test_mmulneg_ew_x(i64 %a1) {
; RV64-LABEL: test_mmulneg_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulneg.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulneg.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmulneg.ew.x(i64, i64, i64)

define void @test_mmulsub_ew_x(i64 %a1) {
; RV64-LABEL: test_mmulsub_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulsub.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulsub.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmulsub.ew.x(i64, i64, i64)

define void @test_mor_ew_x(i64 %a1) {
; RV64-LABEL: test_mor_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mor.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mor.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mor.ew.x(i64, i64, i64)

define void @test_mornot_ew_x(i64 %a1) {
; RV64-LABEL: test_mornot_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mornot.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mornot.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mornot.ew.x(i64, i64, i64)

define void @test_msub_ew_x(i64 %a1) {
; RV64-LABEL: test_msub_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    msub.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.msub.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.msub.ew.x(i64, i64, i64)

define void @test_msublog2_ew_x(i64 %a1) {
; RV64-LABEL: test_msublog2_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    msublog2.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.msublog2.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.msublog2.ew.x(i64, i64, i64)

define void @test_mxor_ew_x(i64 %a1) {
; RV64-LABEL: test_mxor_ew_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mxor.ew.x m1, a0, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mxor.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mxor.ew.x(i64, i64, i64)

define void @test_mmul_2d() {
; RV64-LABEL: test_mmul_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmul.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmul.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmul.2d(i64, i64, i64)

define void @test_mmulacc_2d() {
; RV64-LABEL: test_mmulacc_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulacc.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulacc.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulacc.2d(i64, i64, i64)

define void @test_mmulaccneg_2d() {
; RV64-LABEL: test_mmulaccneg_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulaccneg.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulaccneg.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulaccneg.2d(i64, i64, i64)

define void @test_mmulat_2d() {
; RV64-LABEL: test_mmulat_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulat.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulat.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulat.2d(i64, i64, i64)

define void @test_mmulatacc_2d() {
; RV64-LABEL: test_mmulatacc_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulatacc.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulatacc.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulatacc.2d(i64, i64, i64)

define void @test_mmulbt_2d() {
; RV64-LABEL: test_mmulbt_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulbt.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulbt.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulbt.2d(i64, i64, i64)

define void @test_mmulbtacc_2d() {
; RV64-LABEL: test_mmulbtacc_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulbtacc.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulbtacc.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulbtacc.2d(i64, i64, i64)

define void @test_mmulneg_2d() {
; RV64-LABEL: test_mmulneg_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mmulneg.2d acc1, m2, m3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmulneg.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ztt.mmulneg.2d(i64, i64, i64)

define void @test_mls(ptr %addr) {
; RV64-LABEL: test_mls:
; RV64:       # %bb.0:
; RV64-NEXT:    mls m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mls(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ztt.mls(i64, ptr)

define void @test_mls_cm(ptr %addr) {
; RV64-LABEL: test_mls_cm:
; RV64:       # %bb.0:
; RV64-NEXT:    mls.cm m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mls.cm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ztt.mls.cm(i64, ptr)

define void @test_mls_rm(ptr %addr) {
; RV64-LABEL: test_mls_rm:
; RV64:       # %bb.0:
; RV64-NEXT:    mls.rm m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mls.rm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ztt.mls.rm(i64, ptr)

define void @test_mss(ptr %addr) {
; RV64-LABEL: test_mss:
; RV64:       # %bb.0:
; RV64-NEXT:    mss m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mss(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ztt.mss(i64, ptr)

define void @test_mss_cm(ptr %addr) {
; RV64-LABEL: test_mss_cm:
; RV64:       # %bb.0:
; RV64-NEXT:    mss.cm m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mss.cm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ztt.mss.cm(i64, ptr)

define void @test_mss_rm(ptr %addr) {
; RV64-LABEL: test_mss_rm:
; RV64:       # %bb.0:
; RV64-NEXT:    mss.rm m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mss.rm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ztt.mss.rm(i64, ptr)

define void @test_mzero_2d() {
; RV64-LABEL: test_mzero_2d:
; RV64:       # %bb.0:
; RV64-NEXT:    mzero.2d acc1
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mzero.2d(i64 1)
  ret void
}
declare void @llvm.riscv.ztt.mzero.2d(i64)

define void @test_mmov_a_m() {
; RV64-LABEL: test_mmov_a_m:
; RV64:       # %bb.0:
; RV64-NEXT:    mmov.a.m m1, acc2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmov.a.m(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmov.a.m(i64, i64)

define void @test_mmov_m_m() {
; RV64-LABEL: test_mmov_m_m:
; RV64:       # %bb.0:
; RV64-NEXT:    mmov.m.m m1, m2
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mmov.m.m(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ztt.mmov.m.m(i64, i64)

define i64 @test_mgettyp() {
; RV64-LABEL: test_mgettyp:
; RV64:       # %bb.0:
; RV64-NEXT:    mgettyp a0, m1
; RV64-NEXT:    ret
  %type = call i64 @llvm.riscv.ztt.mgettyp(i64 1)
  ret i64 %type
}
declare i64 @llvm.riscv.ztt.mgettyp(i64)

define i64 @test_agettyp() {
; RV64-LABEL: test_agettyp:
; RV64:       # %bb.0:
; RV64-NEXT:    agettyp a0, acc1
; RV64-NEXT:    ret
  %type = call i64 @llvm.riscv.ztt.agettyp(i64 1)
  ret i64 %type
}
declare i64 @llvm.riscv.ztt.agettyp(i64)

define void @test_msettyp(i64 %a1) {
; RV64-LABEL: test_msettyp:
; RV64:       # %bb.0:
; RV64-NEXT:    msettyp m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.msettyp(i64 1, i64 %a1)
  ret void
}
declare void @llvm.riscv.ztt.msettyp(i64, i64)

define void @test_asettyp(i64 %a1) {
; RV64-LABEL: test_asettyp:
; RV64:       # %bb.0:
; RV64-NEXT:    asettyp acc1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.asettyp(i64 1, i64 %a1)
  ret void
}
declare void @llvm.riscv.ztt.asettyp(i64, i64)

define void @test_mbcast_x(i64 %a1) {
; RV64-LABEL: test_mbcast_x:
; RV64:       # %bb.0:
; RV64-NEXT:    mbcast.x m1, a0
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mbcast.x(i64 1, i64 %a1)
  ret void
}
declare void @llvm.riscv.ztt.mbcast.x(i64, i64)

define void @test_mshift_ew_pos() {
; RV64-LABEL: test_mshift_ew_pos:
; RV64:       # %bb.0:
; RV64-NEXT:    mshift.ew m1, m2, 5
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mshift.ew(i64 1, i64 2, i64 5)
  ret void
}

define void @test_mshift_ew_neg() {
; RV64-LABEL: test_mshift_ew_neg:
; RV64:       # %bb.0:
; RV64-NEXT:    mshift.ew m1, m2, -3
; RV64-NEXT:    ret
  call void @llvm.riscv.ztt.mshift.ew(i64 1, i64 2, i64 -3)
  ret void
}
declare void @llvm.riscv.ztt.mshift.ew(i64, i64, i64)
