; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=+experimental-ztt -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV64

define void @test_mabs_ew() {
  call void @llvm.riscv.ame.mabs.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mabs.ew(i64, i64)

define void @test_mcolunzip_ew() {
  call void @llvm.riscv.ame.mcolunzip.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mcolunzip.ew(i64, i64)

define void @test_mcolzip_ew() {
  call void @llvm.riscv.ame.mcolzip.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mcolzip.ew(i64, i64)

define void @test_mconv_ew() {
  call void @llvm.riscv.ame.mconv.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mconv.ew(i64, i64)

define void @test_mexp2_ew() {
  call void @llvm.riscv.ame.mexp2.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mexp2.ew(i64, i64)

define void @test_mlog2_ew() {
  call void @llvm.riscv.ame.mlog2.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mlog2.ew(i64, i64)

define void @test_mprefixadd_col() {
  call void @llvm.riscv.ame.mprefixadd.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mprefixadd.col(i64, i64)

define void @test_mprefixadd_row() {
  call void @llvm.riscv.ame.mprefixadd.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mprefixadd.row(i64, i64)

define void @test_mprefixmax_col() {
  call void @llvm.riscv.ame.mprefixmax.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mprefixmax.col(i64, i64)

define void @test_mprefixmax_row() {
  call void @llvm.riscv.ame.mprefixmax.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mprefixmax.row(i64, i64)

define void @test_mreduceadd_col() {
  call void @llvm.riscv.ame.mreduceadd.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mreduceadd.col(i64, i64)

define void @test_mreduceadd_row() {
  call void @llvm.riscv.ame.mreduceadd.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mreduceadd.row(i64, i64)

define void @test_mreducemax_col() {
  call void @llvm.riscv.ame.mreducemax.col(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mreducemax.col(i64, i64)

define void @test_mreducemax_row() {
  call void @llvm.riscv.ame.mreducemax.row(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mreducemax.row(i64, i64)

define void @test_mrowunzip_ew() {
  call void @llvm.riscv.ame.mrowunzip.ew(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mrowunzip.ew(i64, i64)

define void @test_mabsdiff_ew() {
  call void @llvm.riscv.ame.mabsdiff.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mabsdiff.ew(i64, i64, i64)

define void @test_madd_ew() {
  call void @llvm.riscv.ame.madd.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.madd.ew(i64, i64, i64)

define void @test_mand_ew() {
  call void @llvm.riscv.ame.mand.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mand.ew(i64, i64, i64)

define void @test_mandnot_ew() {
  call void @llvm.riscv.ame.mandnot.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mandnot.ew(i64, i64, i64)

define void @test_mcmovge_ew() {
  call void @llvm.riscv.ame.mcmovge.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mcmovge.ew(i64, i64, i64)

define void @test_mcmovlt_ew() {
  call void @llvm.riscv.ame.mcmovlt.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mcmovlt.ew(i64, i64, i64)

define void @test_mcmpge_ew() {
  call void @llvm.riscv.ame.mcmpge.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mcmpge.ew(i64, i64, i64)

define void @test_mcmplt_ew() {
  call void @llvm.riscv.ame.mcmplt.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mcmplt.ew(i64, i64, i64)

define void @test_mgather_ew() {
  call void @llvm.riscv.ame.mgather.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mgather.ew(i64, i64, i64)

define void @test_mhdiff_ew() {
  call void @llvm.riscv.ame.mhdiff.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mhdiff.ew(i64, i64, i64)

define void @test_mldexp_ew() {
  call void @llvm.riscv.ame.mldexp.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mldexp.ew(i64, i64, i64)

define void @test_mldexpacc_ew() {
  call void @llvm.riscv.ame.mldexpacc.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mldexpacc.ew(i64, i64, i64)

define void @test_mlog2sub_ew() {
  call void @llvm.riscv.ame.mlog2sub.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mlog2sub.ew(i64, i64, i64)

define void @test_mmax_ew() {
  call void @llvm.riscv.ame.mmax.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmax.ew(i64, i64, i64)

define void @test_mmean_ew() {
  call void @llvm.riscv.ame.mmean.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmean.ew(i64, i64, i64)

define void @test_mmin_ew() {
  call void @llvm.riscv.ame.mmin.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmin.ew(i64, i64, i64)

define void @test_mmul_ew() {
  call void @llvm.riscv.ame.mmul.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmul.ew(i64, i64, i64)

define void @test_mmulacc_ew() {
  call void @llvm.riscv.ame.mmulacc.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulacc.ew(i64, i64, i64)

define void @test_mmulaccneg_ew() {
  call void @llvm.riscv.ame.mmulaccneg.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulaccneg.ew(i64, i64, i64)

define void @test_mmuladd_ew() {
  call void @llvm.riscv.ame.mmuladd.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmuladd.ew(i64, i64, i64)

define void @test_mmulneg_ew() {
  call void @llvm.riscv.ame.mmulneg.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulneg.ew(i64, i64, i64)

define void @test_mmulsub_ew() {
  call void @llvm.riscv.ame.mmulsub.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulsub.ew(i64, i64, i64)

define void @test_mor_ew() {
  call void @llvm.riscv.ame.mor.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mor.ew(i64, i64, i64)

define void @test_mornot_ew() {
  call void @llvm.riscv.ame.mornot.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mornot.ew(i64, i64, i64)

define void @test_mrdexp_ew() {
  call void @llvm.riscv.ame.mrdexp.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mrdexp.ew(i64, i64, i64)

define void @test_mrdexpacc_ew() {
  call void @llvm.riscv.ame.mrdexpacc.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mrdexpacc.ew(i64, i64, i64)

define void @test_mrowzip_ew() {
  call void @llvm.riscv.ame.mrowzip.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mrowzip.ew(i64, i64, i64)

define void @test_mscatadd_col() {
  call void @llvm.riscv.ame.mscatadd.col(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mscatadd.col(i64, i64, i64)

define void @test_mscatadd_row() {
  call void @llvm.riscv.ame.mscatadd.row(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mscatadd.row(i64, i64, i64)

define void @test_mscatmax_col() {
  call void @llvm.riscv.ame.mscatmax.col(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mscatmax.col(i64, i64, i64)

define void @test_mscatmax_row() {
  call void @llvm.riscv.ame.mscatmax.row(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mscatmax.row(i64, i64, i64)

define void @test_mselge_ew() {
  call void @llvm.riscv.ame.mselge.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mselge.ew(i64, i64, i64)

define void @test_msellt_ew() {
  call void @llvm.riscv.ame.msellt.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.msellt.ew(i64, i64, i64)

define void @test_msub_ew() {
  call void @llvm.riscv.ame.msub.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.msub.ew(i64, i64, i64)

define void @test_msublog2_ew() {
  call void @llvm.riscv.ame.msublog2.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.msublog2.ew(i64, i64, i64)

define void @test_mxor_ew() {
  call void @llvm.riscv.ame.mxor.ew(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mxor.ew(i64, i64, i64)

define void @test_mabsdiff_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mabsdiff.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mabsdiff.ew.x(i64, i64, i64)

define void @test_madd_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.madd.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.madd.ew.x(i64, i64, i64)

define void @test_mand_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mand.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mand.ew.x(i64, i64, i64)

define void @test_mandnot_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mandnot.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mandnot.ew.x(i64, i64, i64)

define void @test_mcmpge_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mcmpge.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mcmpge.ew.x(i64, i64, i64)

define void @test_mcmplt_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mcmplt.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mcmplt.ew.x(i64, i64, i64)

define void @test_mhdiff_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mhdiff.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mhdiff.ew.x(i64, i64, i64)

define void @test_mldexp_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mldexp.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mldexp.ew.x(i64, i64, i64)

define void @test_mldexpacc_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mldexpacc.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mldexpacc.ew.x(i64, i64, i64)

define void @test_mlog2sub_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mlog2sub.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mlog2sub.ew.x(i64, i64, i64)

define void @test_mmax_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmax.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmax.ew.x(i64, i64, i64)

define void @test_mmean_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmean.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmean.ew.x(i64, i64, i64)

define void @test_mmin_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmin.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmin.ew.x(i64, i64, i64)

define void @test_mmul_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmul.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmul.ew.x(i64, i64, i64)

define void @test_mmulacc_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmulacc.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmulacc.ew.x(i64, i64, i64)

define void @test_mmulaccneg_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmulaccneg.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmulaccneg.ew.x(i64, i64, i64)

define void @test_mmuladd_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmuladd.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmuladd.ew.x(i64, i64, i64)

define void @test_mmulneg_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmulneg.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmulneg.ew.x(i64, i64, i64)

define void @test_mmulsub_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mmulsub.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmulsub.ew.x(i64, i64, i64)

define void @test_mor_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mor.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mor.ew.x(i64, i64, i64)

define void @test_mornot_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mornot.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mornot.ew.x(i64, i64, i64)

define void @test_msub_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.msub.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.msub.ew.x(i64, i64, i64)

define void @test_msublog2_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.msublog2.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.msublog2.ew.x(i64, i64, i64)

define void @test_mxor_ew_x(i64 %a1) {
  call void @llvm.riscv.ame.mxor.ew.x(i64 1, i64 %a1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mxor.ew.x(i64, i64, i64)

define void @test_mmul_2d() {
  call void @llvm.riscv.ame.mmul.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmul.2d(i64, i64, i64)

define void @test_mmulacc_2d() {
  call void @llvm.riscv.ame.mmulacc.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulacc.2d(i64, i64, i64)

define void @test_mmulaccneg_2d() {
  call void @llvm.riscv.ame.mmulaccneg.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulaccneg.2d(i64, i64, i64)

define void @test_mmulat_2d() {
  call void @llvm.riscv.ame.mmulat.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulat.2d(i64, i64, i64)

define void @test_mmulatacc_2d() {
  call void @llvm.riscv.ame.mmulatacc.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulatacc.2d(i64, i64, i64)

define void @test_mmulbt_2d() {
  call void @llvm.riscv.ame.mmulbt.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulbt.2d(i64, i64, i64)

define void @test_mmulbtacc_2d() {
  call void @llvm.riscv.ame.mmulbtacc.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulbtacc.2d(i64, i64, i64)

define void @test_mmulneg_2d() {
  call void @llvm.riscv.ame.mmulneg.2d(i64 1, i64 2, i64 3)
  ret void
}
declare void @llvm.riscv.ame.mmulneg.2d(i64, i64, i64)

define void @test_mls(ptr %addr) {
  call void @llvm.riscv.ame.mls(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ame.mls(i64, ptr)

define void @test_mls_cm(ptr %addr) {
  call void @llvm.riscv.ame.mls.cm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ame.mls.cm(i64, ptr)

define void @test_mls_rm(ptr %addr) {
  call void @llvm.riscv.ame.mls.rm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ame.mls.rm(i64, ptr)

define void @test_mss(ptr %addr) {
  call void @llvm.riscv.ame.mss(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ame.mss(i64, ptr)

define void @test_mss_cm(ptr %addr) {
  call void @llvm.riscv.ame.mss.cm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ame.mss.cm(i64, ptr)

define void @test_mss_rm(ptr %addr) {
  call void @llvm.riscv.ame.mss.rm(i64 1, ptr %addr)
  ret void
}
declare void @llvm.riscv.ame.mss.rm(i64, ptr)

define void @test_mzero_2d() {
  call void @llvm.riscv.ame.mzero.2d(i64 1)
  ret void
}
declare void @llvm.riscv.ame.mzero.2d(i64)

define void @test_mmov_a_m() {
  call void @llvm.riscv.ame.mmov.a.m(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmov.a.m(i64, i64)

define void @test_mmov_m_m() {
  call void @llvm.riscv.ame.mmov.m.m(i64 1, i64 2)
  ret void
}
declare void @llvm.riscv.ame.mmov.m.m(i64, i64)

define i64 @test_mgettyp() {
  %type = call i64 @llvm.riscv.ame.mgettyp(i64 1)
  ret i64 %type
}
declare i64 @llvm.riscv.ame.mgettyp(i64)

define i64 @test_agettyp() {
  %type = call i64 @llvm.riscv.ame.agettyp(i64 1)
  ret i64 %type
}
declare i64 @llvm.riscv.ame.agettyp(i64)

define void @test_msettyp(i64 %a1) {
  call void @llvm.riscv.ame.msettyp(i64 1, i64 %a1)
  ret void
}
declare void @llvm.riscv.ame.msettyp(i64, i64)

define void @test_asettyp(i64 %a1) {
  call void @llvm.riscv.ame.asettyp(i64 1, i64 %a1)
  ret void
}
declare void @llvm.riscv.ame.asettyp(i64, i64)

define void @test_mbcast_x(i64 %a1) {
  call void @llvm.riscv.ame.mbcast.x(i64 1, i64 %a1)
  ret void
}
declare void @llvm.riscv.ame.mbcast.x(i64, i64)

define void @test_mshift_ew_pos() {
  call void @llvm.riscv.ame.mshift.ew(i64 1, i64 2, i64 5)
  ret void
}

define void @test_mshift_ew_neg() {
  call void @llvm.riscv.ame.mshift.ew(i64 1, i64 2, i64 -3)
  ret void
}
declare void @llvm.riscv.ame.mshift.ew(i64, i64, i64)
